---
repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        name: Check code formatting (black)
        language_version: python3

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        name: Check code formatting (flake8)

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.4.2
    hooks:
      - id: isort
        name: Check the order of your imports (isort)
        additional_dependencies: [toml]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
      - id: mypy

  - repo: https://github.com/PyCQA/doc8
    rev: 0.8.1rc2
    hooks:
      - id: doc8
        name: Checks the style of the documentation (doc8)
        args: [--max-line-length, "100"]

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.24.2
    hooks:
      - id: yamllint
        name: Check YAML syntax (yamllint)
        args: [--strict]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-ast
        name: Check whether files parse a valid Python (check-ast)
      - id: check-docstring-first
        name: Check the docstring placement (check-docstring-first)
      - id: check-toml
        name: Check the TOML syntax (check-toml)
      - id: check-yaml
        name: Check the YAML syntax (check-yaml)
      - id: debug-statements
        name: Check for debugger imports and breakpoints (debug-statements)
      - id: end-of-file-fixer
        name: Fix end of files (end-of-file-fixer)
      - id: trailing-whitespace
        name: Trim trailing whitespace (trailing-whitespace)
